development:
  secret_key_base: <%= ArchiveConfig.SESSION_SECRET %>
 
test:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 
staging:
  secret_key_base: <%= ArchiveConfig.SESSION_SECRET %>

production:
  secret_key_base: <%= ArchiveConfig.SESSION_SECRET %>
  postmark_api_token: <%= ArchiveConfig.POSTMARK_API %>
